eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: bbb-provider-user-api

#  mvc:
#    view:
#      prefix: /public/
#      suffix: .html
#      static-path-pattern: /**
#    resources:
#      static-locations: classpath:/**




#showSql
logging:
  level:
    com:
      example:
        mapper: debug

