eureka:
  client:
    serviceUrl:
      #      defaultZone: http://118.25.187.1:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8801
spring:
  application:
    name: bbb-common-security-server
  mvc:
    view:
      prefix: /public/
      suffix: .html
      static-path-pattern: /**
    resources:
      static-locations: classpath:/**
jwt:
  secret: shdfkjshdkjfhskdf123
  expiration: 100010
  tokenHeader: 1231
  tokenHead: 123123

#showSql
logging:
  level:
    com:
      example:
        mapper: debug
#    root: debug